- hosts: localhost
  become: yes
  connection: local
  gather_facts: false
  tasks:
  - name: Add Docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

  - name: Set up the stable repository
    shell: >
      add-apt-repository
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu
      $(lsb_release -cs)
      stable"

  - name: apt update
    apt:
      update_cache: yes

  - name: apt install builders
    apt:
      name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncurses5-dev
      - libncursesw5-dev
      - llvm
      - xz-utils
      - tk-dev

  - name: apt install tools
    apt:
      name:
      - wget
      - curl
      - unzip
      - git
      - tmux
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - mysql-client
      - postgresql-client
      - sqlite3
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - direnv
      - jq

